# Generated by Django 3.2.6 on 2021-08-07 07:39

from django.db import migrations, models
import django.db.models.deletion
import psqlextra.manager.manager
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('d96a622b-d5bd-4e6a-ad96-c35f31cf8abd'), primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('birthday', models.DateField()),
            ],
            options={
                'db_table': 'clients',
            },
        ),
        migrations.CreateModel(
            name='Wallets',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('d96a622b-d5bd-4e6a-ad96-c35f31cf8abd'), primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.clients')),
            ],
            options={
                'db_table': 'wallets',
            },
        ),
        migrations.CreateModel(
            name='Operations',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('d96a622b-d5bd-4e6a-ad96-c35f31cf8abd'), primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('OUT', 'Outcome'), ('IN', 'Income')], max_length=10)),
                ('date', models.DateTimeField()),
                ('operation_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.wallets')),
            ],
            options={
                'db_table': 'operations',
            },
            managers=[
                ('objects', psqlextra.manager.manager.PostgresManager()),
            ],
        ),
    ]
